application: lassoem
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static/(.*\.(js|css|html))
  static_files: static/\1
  upload: /static/.*

- url: /.*
  script: lassoem.app
