application: lassoem
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /favicon.ico
  static_files: static/favicon_16x16.ico
  upload: static/favicon_16x16.ico

- url: /static
  static_dir: static

- url: /.*
  script: lassoem.app
